package com.base.commons.constants;

import com.base.commons.types.BaseErrorType;

public enum BaseCommonErrorTypes implements BaseErrorType {

    BASE_UNDEFINED_ERROR_STATUS_EXCEPTION("BASE000000"),

    //General Common Error Code
    BASE_UNSUPPORTED_ENCODING_ERROR("BASE000000"),
    BASE_ERROR_PARSING_NUMERIC_STRING("BASE000010"),

    //Resource Handler Error Codes
    BASE_RESOURCE_HANDLER_PLAIN_STRING_CONTENT_NOT_FOUND_ERROR("BASE000030"),
    BASE_RESOURCE_HANDLER_PLAIN_STRING_CONTENT_LOADING_EXCEPTION_ERROR("BASE000040"),
    BASE_RESOURCE_HANDLER_JSON_MAP_CONFIG_CONTENT_NOT_FOUND_ERROR("BASE000050"),
    BASE_RESOURCE_HANDLER_JSON_MAP_CONFIG_CONTENT_LOADING_EXCEPTION_ERROR("BASE000060"),
    BASE_RESOURCE_HANDLER_JSON_MAP_CONFIG_NO_CACHE_CONTENT_NOT_FOUND_ERROR("BASE000070"),
    BASE_RESOURCE_HANDLER_JSON_MAP_CONFIG_NO_CACHE_CONTENT_LOADING_EXCEPTION_ERROR("BASE000080"),
    BASE_RESOURCE_HANDLER_PROPERTIES_CONTENT_NOT_FOUND_ERROR("BASE000090"),
    BASE_RESOURCE_HANDLER_PROPERTIES_CONTENT_LOADING_EXCEPTION_ERROR("BASE000100"),
    BASE_RESOURCE_HANDLER_PROPERTIES_CONTENT_PROPERTY_NOT_FOUND_ERROR("BASE000260"),
    BASE_RESOURCE_HANDLER_PROPERTIES_PROPERTY_LOADING_EXCEPTION_ERROR("BASE000270"),
    BASE_RESOURCE_HANDLER_JSON_NODE_CONTENT_NOT_FOUND_ERROR("BASE000110"),
    BASE_RESOURCE_HANDLER_JSON_NODE_CONTENT_LOADING_EXCEPTION_ERROR("BASE000120"),
    BASE_RESOURCE_HANDLER_JSON_OBJECT_CONTENT_NOT_FOUND_ERROR("BASE000130"),
    BASE_RESOURCE_HANDLER_JSON_OBJECT_CONTENT_LOADING_EXCEPTION_ERROR("BASE000140"),
    BASE_RESOURCE_HANDLER_XML_OBJECT_CONTENT_NOT_FOUND_ERROR("BASE000150"),
    BASE_RESOURCE_HANDLER_XML_OBJECT_CONTENT_LOADING_EXCEPTION_ERROR("BASE000160"),
    BASE_RESOURCE_HANDLER_INPUT_STREAM_OBJECT_CONTENT_NOT_FOUND_ERROR("BASE000170"),
    BASE_RESOURCE_HANDLER_INPUT_STREAM_OBJECT_CONTENT_LOADING_EXCEPTION_ERROR("BASE000180"),

    //Context
    BASE_CONTEXT_USER_CONTEXT_OBJECT_NOT_FOUND_EXCEPTION_ERROR("BASE000190"),

    //MAPPERS
    BASE_XML_MAPPERS_UTIL_PARSING_XML_STRING_EXCPETION("BASE000200"),
    BASE_JSON_MAPPERS_UTIL_PARSING_JSON_MAP_STRING_EXCPETION("BASE000210"),
    BASE_JSON_MAPPERS_UTIL_PARSING_JSON_STRING_EXCPETION("BASE000220"),
    BASE_JSON_MAPPERS_UTIL_SERIALIZING_JSON_OBJECT_EXCPETION("BASE000230"),
    BASE_JSON_MAPPERS_UTIL_SERIALIZING_INVALID_OBJECT_EXCPETION("BASE000240"),
    BASE_JSON_MAPPERS_UTIL_SERIALIZING_OBJECT_TO_PLAIN_JSON_EXCPETION("BASE000250");

    String errorCode;

    private BaseCommonErrorTypes(String errorCode) {
        this.errorCode = errorCode;
    }

    @Override
    public String getValue() {
        return this.errorCode;
    }
}
